### ISSUE TITLE
请问一下包的版本问题

### ISSUE THREAD

**Issue by xzq-2000** [lll143653/amsnet#1]
AttributeError: module 'torchvision.transforms.v2' has no attribute 'ToImage'. Did you mean: 'ToImagePIL'?
我在环境的配置上遇到一些版本问题，想咨询一下你的各种包的版本，谢谢

**Comment by kaiq663** [comment]
你得按照作者要求重装下环境，注意下torch与torchvison版本匹配问题就好，我没出现过这个问题

**Comment by xzq-2000** [comment]
已经弄好了谢谢，更新了一下torchvision的版本就可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月22日(周一) 下午3:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lll143653/amsnet] 请问一下包的版本问题 (Issue #1)




 
你得按照作者要求重装下环境，注意下torch与torchvison版本匹配问题就好，我没出现过这个问题

**Comment by xzq-2000** [comment]
请问一下您下载成功DND数据集了吗，我一直没有下载成功，如果有的话可以发我一份吗，不胜感激



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月22日(周一) 下午3:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lll143653/amsnet] 请问一下包的版本问题 (Issue #1)




 
你得按照作者要求重装下环境，注意下torch与torchvison版本匹配问题就好，我没出现过这个问题
