### ISSUE TITLE
how to use PolyU with Restormer  as denoiser in AMSNet?do u crop before?

### ISSUE THREAD

**Issue by kaiq663** [lll143653/amsnet#2]
Following configs/val/others/Deamnet2NoisyImagePair.yaml,  a Restormer2NoisyImagePair.yaml is created.

describe: > 
 test polyu with restormer
name: restormer-polyu
output_path: ./outputs/val
epochs: 100
val_check_interval: 1.0
model:
  name: mmpn
  params:
    pd_train: 5
    pd_val: 2
    dn_net: mmbd
    r3: 0.16
    net_param:
      branch_num: 1
      dn_branch: Restormer
      branches_order: [0,0]
      net_param:
        inp_channels: 3
        out_channels: 3
        dim: 48
        num_blocks: [4,6,6,8]
        num_refinement_blocks: 4
        heads: [1,2,4,8]
        ffn_expansion_factor: 2.66
        bias: False
        LayerNorm_type: 'BiasFree'
        dual_pixel_task: False
  checkpoint_path: weights/restormer-sidd-val_avg_psnr=37.92.ckpt

test:
  type: PairDataset
  dataset:
    data_cfgs:
      input:
        path: ../PolyU/noisy_img
        type: image
      target:
        path: ../PolyU/clean_img
        type: image
    max_len: 10000000
    crop_size: -1
  dataloader:
    batch_size: 1
    shuffle: False
   
Then,  ‘python DNE2E.py --config ./configs/val/others/Restormer2NoisyImagePair.yaml’ is typed . Surpringly, an error arised, torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.99 GiB. GPU 0 has a total capacty of 23.63 GiB of which 1.42 GiB is free. My questions are as follows.

question1, the original resolution of PolyU is 512x512, do you crop it to 256x256 or any other resolution?

question2, if not, how to use PolyU with Restormer as denoiser in AMSNet to get 37.92/0.9675 presented in Table2?what do I miss?

**Comment by lll143653** [comment]
sry，i will update a config yaml file

**Comment by lll143653** [comment]
Q1: yeah, i have crop it during train, 24GB is not enough for full image when use restormer as denoiser
Q2: in order to get the best results on polyu, I added polyu to the train dataset and train a long time (about 5 days?),also,during test, set the pd val to 1(polyu has low noise level and dont need pd)
